### ISSUE TITLE
Git Hub Action Configuration - rename job from "build" to "end2end" or "test" 

### ISSUE THREAD

**Issue by safo-bora** [sandro-ua/nasa-api#2]
https://github.com/sandro-ua/nasa-api/blob/0db37e33c59f96508fc5fab2267e2edd756b6b75/.github/workflows/python-app.yml#L16C3-L16C8\
\
<img width="540" alt="Screenshot 2024-02-26 at 11 14 27" src="https://github.com/sandro-ua/nasa-api/assets/4173393/e4b47b39-05b8-411b-a1ee-1d534651ad08">

**Comment by sandro-ua** [comment]
Fixed: https://github.com/sandro-ua/nasa-api/compare/58851dd32719b5e13d432233b8d6fdbf2b76dca7...ad83e75e19cb234db88f8d7acd4163594d817c06

![Untitled](https://github.com/sandro-ua/nasa-api/assets/12571747/730d8b2e-f9bc-42c0-a806-62949d386ce0)
