### ISSUE TITLE
Never hard code KEY 

### ISSUE THREAD

**Issue by safo-bora** [sandro-ua/nasa-api#3]
https://github.com/sandro-ua/nasa-api/blob/0db37e33c59f96508fc5fab2267e2edd756b6b75/tests/epic_tests.py#L5C17-L5C57

- Please move KEY to the ENV variable when running the test locally or to some file that was added to GitHub ignore 

- On CI use Secret - https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

**Comment by sandro-ua** [comment]
changed here for GitHubActions:
https://github.com/sandro-ua/nasa-api/commit/9717aab3f916f42c2af80c2b77de3e8f5dc4d58c
then fixed missed os import issue
https://github.com/sandro-ua/nasa-api/commit/8b79bcd1c258c1dcbf65c8a6dd39842432ac8789
