### ISSUE TITLE
Add logger,  better to not use print() in test frameworks

### ISSUE THREAD

**Issue by safo-bora** [sandro-ua/nasa-api#6]
https://github.com/sandro-ua/nasa-api/blob/0db37e33c59f96508fc5fab2267e2edd756b6b75/tests/epic_tests.py#L19

Please add logger - https://docs.python.org/uk/3/library/logging.html

This approach adheres to best practices by leveraging Python's built-in logging module, which provides a flexible framework for emitting log messages from Python programs. This module is part of the standard Python library and is designed for easy logging setup and use.

**Comment by sandro-ua** [comment]
logger.py file added
now logs are written into file and console
